# Generated by Django 4.2.24 on 2025-09-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='club',
            name='lead_contact',
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_coordinator_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='president_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='president_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='treasurer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='vice_president_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='faculty_coordinator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
